# vi: ts=2 sw=2 et:

extraction:
  cpp:
    prepare:
      # package list copied from .github/workflows/check.yml
      packages:
        - libglib2.0
        - attr
        - automake
        - gettext
        - autopoint
        - bison
        - dbus
        - gtk-doc-tools
        - libfuse-dev
        - ostree
        - libostree-dev
        - libarchive-dev
        - libcap-dev
        - libattr1-dev
        - libdw-dev
        - libelf-dev
        - python3-pyparsing
        - libjson-glib-dev
        - shared-mime-info
        - desktop-file-utils
        - libpolkit-agent-1-dev
        - libpolkit-gobject-1-dev
        - libseccomp-dev
        - libsoup2.4-dev
        - libsystemd-dev
        - libxml2-utils
        - libgpgme11-dev
        - gobject-introspection
        - libgirepository1.0-dev
        - libappstream-glib-dev
        - libdconf-dev
        - socat
        - libdbus-1-dev
        - e2fslibs-dev
    after_prepare:
      - mkdir -p $LGTM_WORKSPACE/installdir
      - git clone https://github.com/ostreedev/ostree.git ./ostree
      - pushd ./ostree
      - git checkout abbe7ea4e7b55ebbbf1a62f6255ce98f399837aa
      - ./autogen.sh --prefix=$LGTM_WORKSPACE/installdir/usr --libdir=$LGTM_WORKSPACE/installdir/usr/lib --sysconfdir=$LGTM_WORKSPACE/installdir/etc --localstatedir=$LGTM_WORKSPACE/installdir/var --without-libsystemd
      - make -j $(getconf _NPROCESSORS_ONLN)
      - make install
      - popd
      - export PKG_CONFIG_PATH=$LGTM_WORKSPACE/installdir/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - export LD_LIBRARY_PATH=$LGTM_WORKSPACE/installdir/usr/lib:$LD_LIBRARY_PATH
